<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;
use App\Models\AdoptionApplication;
use App\Models\User;
use App\Models\Pet;

class AdoptionApplicationSeeder extends Seeder {

    public function run(): void {
        // Define manual predefined adoption applications
        $adoptionRequests = [
            [
                'ApplicationDate' => Carbon::now()->subDays(10),
                'AdoptionStatus' => 'Pending',
                'AdopterID' => 2,
                'PetID' => 1,
                'FullName' => 'John Doe',
                'Age' => 30,
                'Gender' => 'Male',
                'Address' => 'No. 15, Jalan Example, Town',
                'Postcode' => '54321',
                'State' => 'Selangor',
                'ContactNumber' => '0123456789',
                'Email' => 'john.doe@example.com',
                'Occupation' => 'Engineer',
                'HouseholdDetails' => 'Living in an apartment, landlord allows pets.',
                'OtherPetsInfo' => 'No other pets in the household.',
                'ReasonForAdoption' => 'Wants to provide a loving home.',
                'PetCarePlan' => 'Will take the pet for daily walks.',
                'EmergencyPlan' => 'Has savings for emergencies.',
                'SpayNeuterAgreement' => 1,
                'ReturnAgreement' => 1,
                'ReferenceName' => 'Jane Smith',
                'ReferenceContact' => '0198765432',
                'ReferenceRelationship' => 'Friend',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ApplicationDate' => Carbon::now()->subDays(20),
                'AdoptionStatus' => 'Approved',
                'AdopterID' => 2,
                'PetID' => 2,
                'FullName' => 'Sarah Lee',
                'Age' => 25,
                'Gender' => 'Female',
                'Address' => 'No. 42, Jalan Pet Adoption, City',
                'Postcode' => '12345',
                'State' => 'Kuala Lumpur',
                'ContactNumber' => '0187654321',
                'Email' => 'sarah.lee@example.com',
                'Occupation' => 'Teacher',
                'HouseholdDetails' => 'Owns a house with a backyard.',
                'OtherPetsInfo' => 'Has 1 cat.',
                'ReasonForAdoption' => 'Loves animals and wants to adopt.',
                'PetCarePlan' => 'Regular vet checkups.',
                'EmergencyPlan' => 'Emergency fund for pet care.',
                'SpayNeuterAgreement' => 1,
                'ReturnAgreement' => 1,
                'ReferenceName' => 'Michael Tan',
                'ReferenceContact' => '0171234567',
                'ReferenceRelationship' => 'Colleague',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ApplicationDate' => Carbon::now()->subDays(30),
                'AdoptionStatus' => 'Rejected',
                'AdopterID' => 3,
                'PetID' => 3,
                'FullName' => 'Alex Wong',
                'Age' => 40,
                'Gender' => 'Male',
                'Address' => 'No. 33, Jalan Love Pet, Village',
                'Postcode' => '67890',
                'State' => 'Penang',
                'ContactNumber' => '0169876543',
                'Email' => 'alex.wong@example.com',
                'Occupation' => 'Doctor',
                'HouseholdDetails' => 'Lives alone in an apartment.',
                'OtherPetsInfo' => 'Previously owned pets but none currently.',
                'ReasonForAdoption' => 'Lifelong dream to own a pet.',
                'PetCarePlan' => 'Will provide premium pet care.',
                'EmergencyPlan' => 'Pet insurance available.',
                'SpayNeuterAgreement' => 1,
                'ReturnAgreement' => 1,
                'ReferenceName' => 'David Tan',
                'ReferenceContact' => '0157654321',
                'ReferenceRelationship' => 'Neighbor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ApplicationDate' => Carbon::now()->subDays(15),
                'AdoptionStatus' => 'Under Review',
                'AdopterID' => 4,
                'PetID' => 14,
                'FullName' => 'Ng Poh Ling',
                'Age' => 28,
                'Gender' => 'Female',
                'Address' => 'No. 25, Jalan Paw Haven, Town',
                'Postcode' => '33445',
                'State' => 'Johor',
                'ContactNumber' => '0149876543',
                'Email' => 'lingpoh@icloud.com',
                'Occupation' => 'Nurse',
                'HouseholdDetails' => 'Lives with family who support pet adoption.',
                'OtherPetsInfo' => 'Owns a parrot.',
                'ReasonForAdoption' => 'Believes in rescuing animals.',
                'PetCarePlan' => 'Will adopt training methods for pet.',
                'EmergencyPlan' => 'Has access to pet emergency services.',
                'SpayNeuterAgreement' => 1,
                'ReturnAgreement' => 1,
                'ReferenceName' => 'Sophia Lim',
                'ReferenceContact' => '0191122334',
                'ReferenceRelationship' => 'Friend',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ApplicationDate' => now()->subDays(10),
                'AdoptionStatus' => 'Pending',
                'AdopterID' => 3,
                'PetID' => 1, // Ensure this pet exists in the DB
                'FullName' => 'John Doe',
                'Age' => 30,
                'Gender' => 'Male',
                'Address' => 'No. 15, Jalan Example, Town',
                'Postcode' => '54321',
                'State' => 'Selangor',
                'ContactNumber' => '0123456789',
                'Email' => 'john.doe@example.com',
                'Occupation' => 'Engineer',
                'HouseholdDetails' => 'Living in an apartment, landlord allows pets.',
                'OtherPetsInfo' => 'No other pets in the household.',
                'ReasonForAdoption' => 'Wants to provide a loving home.',
                'PetCarePlan' => 'Will take the pet for daily walks.',
                'EmergencyPlan' => 'Has savings for emergencies.',
                'SpayNeuterAgreement' => 1,
                'ReturnAgreement' => 1,
                'ReferenceName' => 'Jane Smith',
                'ReferenceContact' => '0198765432',
                'ReferenceRelationship' => 'Friend',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ApplicationDate' => now()->subDays(20),
                'AdoptionStatus' => 'Approved',
                'AdopterID' => 4,
                'PetID' => 4,
                'FullName' => 'Ng Poh Ling',
                'Age' => 25,
                'Gender' => 'Female',
                'Address' => 'No. 42, Jalan Pet Adoption, City',
                'Postcode' => '12345',
                'State' => 'Kuala Lumpur',
                'ContactNumber' => '0187654321',
                'Email' => 'lingpoh@icloud.com',
                'Occupation' => 'Teacher',
                'HouseholdDetails' => 'Owns a house with a backyard.',
                'OtherPetsInfo' => 'Has 1 cat.',
                'ReasonForAdoption' => 'Loves animals and wants to adopt.',
                'PetCarePlan' => 'Regular vet checkups.',
                'EmergencyPlan' => 'Emergency fund for pet care.',
                'SpayNeuterAgreement' => 1,
                'ReturnAgreement' => 1,
                'ReferenceName' => 'Michael Tan',
                'ReferenceContact' => '0171234567',
                'ReferenceRelationship' => 'Colleague',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        // Insert adoption applications into the database
        DB::table('adoption_applications')->insert($adoptionRequests);

        $this->command->info(count($adoptionRequests) . ' adoption applications seeded successfully!');
    }
}
